/**
 * Blog index + article pages for SEO content marketing.
 * Route: /blog and /blog/:slug
 */

import { useParams, Link } from "react-router-dom";
import { useEffect } from "react";
import { Button } from "@/components/ui/button";
import { ArrowRight, ArrowLeft, Calendar, Clock } from "lucide-react";
import Logo from "@/components/Logo";

interface BlogPost {
  slug: string;
  title: string;
  metaDescription: string;
  date: string;
  readTime: string;
  category: string;
  content: string;
}

const POSTS: BlogPost[] = [
  {
    slug: "best-ai-trip-planner-2026",
    title: "Best AI Trip Planner in 2026: What Actually Works",
    metaDescription: "Honest comparison of AI trip planners in 2026. We tested Jolliday, Layla AI, Wonderplan, ChatGPT, and more to find which ones generate real, bookable itineraries vs. generic lists.",
    date: "2026-05-15",
    readTime: "6 min",
    category: "Comparison",
    content: `## The AI Trip Planner Landscape in 2026

The market for AI trip planners has exploded. Every week there's a new tool promising to "plan your trip in seconds." But most of them generate the same generic suggestions you'd find on any travel blog.

We tested the leading AI trip planners on the same request: "Plan a 4-day trip to Barcelona for a couple, mid-range budget, love food and architecture." Here's what actually works.

## What Makes a Good AI Trip Planner?

Before diving into tools, here's what separates useful from useless:

- **Verified venues** — Does it recommend places that actually exist? Many AI planners hallucinate restaurant names.
- **Real pricing** — Does it show actual flight/hotel costs, or made-up numbers?
- **Bookable output** — Can you actually book what it suggests, or do you need to start over on Booking.com?
- **Day-by-day structure** — A list of "top 10 things to do" isn't a plan. You need time slots, neighborhoods, and logical routing.
- **Personalization** — Does it adapt to your budget, travel style, and group type?

## The Contenders

### Jolliday
**Strengths:** Generates complete day-by-day itineraries with real venues verified against Google Places. Shows real-time flight and hotel prices via Travelpayouts. Walking times between venues calculated via OSRM. Direct booking links to Skyscanner, Booking.com, and GetYourGuide.

**Weaknesses:** Web-only (no native app yet). Requires a subscription after free trial.

**Verdict:** The most complete output — you get an actually bookable plan, not just inspiration.

### Layla AI
**Strengths:** Clean visual interface, Skyscanner/Booking.com partnerships, conversation-style refinement.

**Weaknesses:** $50/year paywall for key features. No walking route intelligence. Venue verification is hit-or-miss.

### Wonderplan
**Strengths:** Completely free. Good budget tracking. Fast generation.

**Weaknesses:** No real pricing data. Venues aren't verified. Output is more of a suggestion list than a structured plan.

### ChatGPT / Gemini
**Strengths:** Most flexible — handles complex multi-constraint requests. Good for brainstorming.

**Weaknesses:** No booking links. No real prices. No venue verification. You still need to do all the actual planning work.

## Our Recommendation

If you want an itinerary you can actually follow and book from, tools that verify venues and show real prices save you hours of cross-referencing. For pure brainstorming and inspiration, ChatGPT is unbeatable. For the sweet spot — a complete, verified, bookable plan in under a minute — dedicated AI trip planners deliver more value.

[Plan your next trip with AI →](https://jolliday.online/chat)`,
  },
  {
    slug: "3-days-barcelona-itinerary",
    title: "3 Days in Barcelona: AI-Planned Itinerary (2026)",
    metaDescription: "Complete 3-day Barcelona itinerary planned by AI. Day-by-day schedule with the best restaurants, activities, neighborhoods, and tips for couples and solo travelers.",
    date: "2026-05-10",
    readTime: "8 min",
    category: "Destination Guide",
    content: `## Your AI-Planned Barcelona Itinerary

Barcelona is one of Europe's most popular destinations — and for good reason. Gaudí's architecture, incredible food, Mediterranean beaches, and vibrant nightlife create a city that has something for everyone.

Here's a day-by-day itinerary generated by Jolliday AI for a couple visiting Barcelona in spring.

## Day 1: Gothic Quarter & Waterfront

**Morning**
- Breakfast at Federal Café (Gòtic) — specialty coffee and brunch
- Walk through the Gothic Quarter's medieval streets
- Visit Barcelona Cathedral

**Afternoon**
- La Boqueria market for tapas lunch
- Walk down Las Ramblas to the waterfront
- Explore Barceloneta Beach and the Port area

**Evening**
- Dinner at Can Paixano (local cava bar)
- Rooftop drinks at Hotel Ohla

## Day 2: Gaudí & Eixample

**Morning**
- Sagrada Familia (book tickets in advance — sells out weeks ahead)
- Walk through Eixample's grid streets admiring modernist facades

**Afternoon**
- Lunch at Cervecería Catalana (one of the city's best tapas bars)
- Casa Batlló or Casa Milà (choose one — both are stunning)
- Park Güell for sunset views

**Evening**
- Dinner in Gràcia neighborhood (try La Pepita for creative tapas)
- Evening walk along Passeig de Gràcia

## Day 3: El Born & Local Life

**Morning**
- Breakfast at Nomad Coffee (Born)
- Picasso Museum (pre-book)
- Shop along Carrer del Rec

**Afternoon**
- Lunch at El Xampanyet (standing-room-only cava bar since 1929)
- Ciutadella Park for a break
- Explore the Santa Caterina Market (less tourist-heavy than La Boqueria)

**Evening**
- Sunset at Bunkers del Carmel (best secret viewpoint in the city)
- Farewell dinner at Cal Pep (seafood tapas)

## Budget Estimate (per person)

- Flights from major European cities: €50-150 return
- 3-star hotel in Born/Eixample: €80-130/night
- Food: €40-60/day
- Activities & entry fees: €30-50/day

**Total for 2 people, 3 nights: approximately €800-1,200**

## Tips

1. Book Sagrada Familia and Park Güell tickets online at least 2 weeks ahead
2. Avoid Las Ramblas restaurants — walk one street parallel for better food at half the price
3. The metro (T-Casual card) is the best way to get between neighborhoods
4. Restaurants open late — dinner before 20:30 marks you as a tourist

Want a personalized version of this itinerary with real-time prices and booking links?

[Plan my Barcelona trip →](https://jolliday.online/chat?q=3+days+in+Barcelona+for+a+couple)`,
  },
  {
    slug: "how-to-plan-trip-with-ai",
    title: "How to Plan a Trip with AI (Complete Guide 2026)",
    metaDescription: "Learn how to use AI to plan your next trip. Step-by-step guide covering the best prompts, what to expect from AI trip planners, and how to get a complete bookable itinerary.",
    date: "2026-05-01",
    readTime: "5 min",
    category: "Guide",
    content: `## Why Plan Trips with AI?

The average person spends 30+ hours researching a single vacation across dozens of browser tabs. AI trip planners compress that into under a minute.

But there's a catch: the quality varies enormously depending on how you use them and which tool you choose.

## How AI Trip Planning Works

Modern AI trip planners like Jolliday take your plain-language description and generate a structured itinerary. The best ones:

1. **Ask clarifying questions** — destination, dates, budget, travel style, group size
2. **Generate a complete plan** — flights, hotels, day-by-day activities, restaurants
3. **Verify the output** — check that recommended venues actually exist
4. **Add real data** — actual flight prices, hotel rates, walking distances
5. **Provide booking links** — so you can book everything without starting over

## The Perfect Prompt

The more specific you are, the better the result. Here's the anatomy of a great AI trip planning prompt:

**Basic (mediocre result):**
> "Plan a trip to Italy"

**Good (decent result):**
> "5 days in Rome for a couple"

**Great (excellent result):**
> "5 days in Rome for a couple, mid-range budget around €150/day, we love food and history but want some relaxation too. Traveling May 15-20, flying from Berlin."

The key ingredients:
- **Destination** (specific city, not just country)
- **Duration** (exact days)
- **Who's going** (couple, family with kids ages, solo, friends)
- **Budget** (even approximate helps)
- **Interests/vibe** (food, adventure, relaxation, nightlife)
- **Dates** (affects pricing, weather, and availability)
- **Origin city** (for accurate flight suggestions)

## What to Expect from the Output

A quality AI trip planner should give you:

- ✅ Day-by-day schedule with specific times
- ✅ Named venues (not "a nice restaurant" but "Osteria Francescana")
- ✅ Logical geographic routing (not zig-zagging across the city)
- ✅ Real price estimates
- ✅ Direct booking links
- ✅ All three meals each day
- ✅ Mix of popular sights and hidden gems

Red flags that mean the AI is hallucinating:
- ❌ Restaurant names you can't find on Google
- ❌ Exact prices down to the cent (real prices fluctuate)
- ❌ Generic descriptions like "enjoy the local cuisine"
- ❌ Activities that are logistically impossible (visiting two cities in one afternoon)

## Tips for Better Results

1. **Be specific about your vibe** — "romantic" produces very different results than "adventure"
2. **Mention dietary restrictions** — good AI will silently filter inappropriate restaurants
3. **Ask for modifications** — "make day 2 more relaxed" or "swap the dinner for somewhere cheaper"
4. **Check the map** — make sure the daily route makes geographic sense
5. **Book early** — AI recommendations for popular venues often require advance booking

## Try It Now

The fastest way to understand AI trip planning is to try it. Describe your next trip and see what happens:

[Start planning with AI →](https://jolliday.online/chat)`,
  },
];

const BlogIndex = () => {
  useEffect(() => {
    document.title = "Travel Planning Blog — AI Tips & Destination Guides | Jolliday";
  }, []);

  return (
    <div className="min-h-screen bg-background">
      <header className="sticky top-0 z-50 bg-background/95 backdrop-blur-sm border-b border-border">
        <div className="max-w-4xl mx-auto px-4 py-3 flex items-center justify-between">
          <Link to="/"><Logo size="sm" /></Link>
          <Link to="/chat"><Button size="sm" className="rounded-full gap-1.5">Plan a trip <ArrowRight className="h-3.5 w-3.5" /></Button></Link>
        </div>
      </header>
      <div className="max-w-4xl mx-auto px-4 py-12">
        <h1 className="text-4xl font-extrabold tracking-tight mb-3">Travel Planning Blog</h1>
        <p className="text-lg text-muted-foreground mb-10">Tips, guides, and comparisons to help you plan better trips with AI.</p>
        <div className="space-y-8">
          {POSTS.map(post => (
            <Link key={post.slug} to={`/blog/${post.slug}`} className="block group">
              <article className="p-6 rounded-2xl border border-border bg-card hover:border-primary/30 hover:shadow-lg transition-all">
                <div className="flex items-center gap-3 mb-3 text-xs text-muted-foreground">
                  <span className="px-2 py-0.5 rounded-full bg-primary/5 text-primary font-medium">{post.category}</span>
                  <span className="flex items-center gap-1"><Calendar className="h-3 w-3" /> {post.date}</span>
                  <span className="flex items-center gap-1"><Clock className="h-3 w-3" /> {post.readTime}</span>
                </div>
                <h2 className="text-xl font-bold text-foreground group-hover:text-primary transition-colors mb-2">{post.title}</h2>
                <p className="text-sm text-muted-foreground">{post.metaDescription}</p>
              </article>
            </Link>
          ))}
        </div>
      </div>
    </div>
  );
};

const BlogArticle = () => {
  const { slug } = useParams<{ slug: string }>();
  const post = POSTS.find(p => p.slug === slug);

  useEffect(() => {
    if (post) {
      document.title = `${post.title} | Jolliday Blog`;
      const meta = document.querySelector('meta[name="description"]');
      if (meta) meta.setAttribute("content", post.metaDescription);
    }
  }, [post]);

  if (!post) return <div className="p-8 text-center">Post not found</div>;

  return (
    <div className="min-h-screen bg-background">
      <header className="sticky top-0 z-50 bg-background/95 backdrop-blur-sm border-b border-border">
        <div className="max-w-3xl mx-auto px-4 py-3 flex items-center justify-between">
          <Link to="/blog" className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground">
            <ArrowLeft className="h-4 w-4" /> Blog
          </Link>
          <Link to="/chat"><Button size="sm" className="rounded-full gap-1.5">Plan a trip <ArrowRight className="h-3.5 w-3.5" /></Button></Link>
        </div>
      </header>
      <article className="max-w-3xl mx-auto px-4 py-12">
        <div className="flex items-center gap-3 mb-4 text-xs text-muted-foreground">
          <span className="px-2 py-0.5 rounded-full bg-primary/5 text-primary font-medium">{post.category}</span>
          <span>{post.date}</span>
          <span>{post.readTime} read</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight mb-8">{post.title}</h1>
        <div className="prose prose-neutral max-w-none [&_h2]:text-2xl [&_h2]:font-bold [&_h2]:mt-10 [&_h2]:mb-4 [&_h3]:text-xl [&_h3]:font-bold [&_h3]:mt-8 [&_h3]:mb-3 [&_p]:text-base [&_p]:leading-relaxed [&_p]:text-muted-foreground [&_p]:mb-4 [&_li]:text-muted-foreground [&_strong]:text-foreground [&_a]:text-primary [&_a]:underline [&_blockquote]:border-l-4 [&_blockquote]:border-primary/30 [&_blockquote]:pl-4 [&_blockquote]:italic">
          {post.content.split("\n\n").map((block, i) => {
            if (block.startsWith("## ")) return <h2 key={i}>{block.slice(3)}</h2>;
            if (block.startsWith("### ")) return <h3 key={i}>{block.slice(4)}</h3>;
            if (block.startsWith("- ")) return <ul key={i}>{block.split("\n").map((li, j) => <li key={j}>{li.slice(2)}</li>)}</ul>;
            if (block.startsWith("> ")) return <blockquote key={i}><p>{block.slice(2)}</p></blockquote>;
            if (block.startsWith("[")) {
              const match = block.match(/\[(.+?)\]\((.+?)\)/);
              if (match) return <p key={i}><a href={match[2]}>{match[1]}</a></p>;
            }
            return <p key={i}>{block}</p>;
          })}
        </div>
      </article>
    </div>
  );
};

const Blog = () => {
  const { slug } = useParams<{ slug?: string }>();
  if (slug) return <BlogArticle />;
  return <BlogIndex />;
};

export default Blog;
