import jsPDF from "jspdf";
import { TripPlanData } from "@/components/TripSummaryCard";

type LegacyTripData = {
  title: string;
  messages: { role: string; content: string }[];
};

// Legacy export for chat messages
export const exportTripPDF = (data: LegacyTripData) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let y = 20;

  const addPage = () => { doc.addPage(); y = 20; };
  const checkPage = (needed: number) => {
    if (y + needed > doc.internal.pageSize.getHeight() - 20) addPage();
  };

  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text(data.title, margin, y);
  y += 10;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120);
  doc.text(`Generated by Jolliday • ${new Date().toLocaleDateString()}`, margin, y);
  y += 12;
  doc.setTextColor(0);

  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  const assistantMessages = data.messages
    .filter((m) => m.role === "assistant")
    .map((m) => m.content.replace(/```[\s\S]*?```/g, "").trim())
    .filter(Boolean);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");

  assistantMessages.forEach((msg, i) => {
    checkPage(20);
    if (i > 0) { doc.setDrawColor(230); doc.line(margin, y, pageWidth - margin, y); y += 8; }
    const lines = doc.splitTextToSize(msg, maxWidth);
    lines.forEach((line: string) => { checkPage(7); doc.text(line, margin, y); y += 6; });
    y += 6;
  });

  checkPage(20);
  y += 10;
  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text("Jolliday — Your AI Travel Companion", margin, y);

  doc.save(`${data.title.replace(/\s+/g, "-").toLowerCase()}-trip-plan.pdf`);
};

// Structured export for TripPlanData
export const exportTripPlanPDF = ({ data, destination }: { data: TripPlanData; destination: string }) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let y = 20;

  const addPage = () => { doc.addPage(); y = 20; };
  const checkPage = (needed: number) => {
    if (y + needed > pageHeight - 20) addPage();
  };

  const sectionTitle = (title: string) => {
    checkPage(20);
    y += 6;
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(40);
    doc.text(title, margin, y);
    y += 2;
    doc.setDrawColor(200);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(60);
  };

  // Header
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30);
  doc.text(destination, margin, y);
  y += 10;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120);
  const meta = [`Generated by Jolliday • ${new Date().toLocaleDateString()}`];
  if (data.itinerary.length) meta.push(`${data.itinerary.length} days`);
  doc.text(meta.join("  |  "), margin, y);
  y += 8;

  doc.setDrawColor(180);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  // Quick Info
  if (data.travelInfo) {
    sectionTitle("Travel Info");
    const info = data.travelInfo;
    const infoLines = [
      `Visa: ${info.visa}`,
      `Currency: ${info.currency}`,
      `Language: ${info.language}`,
      `Timezone: ${info.timezone}`,
      `Best Season: ${info.bestSeason}`,
    ].filter(l => !l.endsWith("undefined"));
    infoLines.forEach(line => {
      checkPage(7);
      doc.text(line, margin, y);
      y += 6;
    });
    y += 4;
  }

  // Flights
  if (data.flights.length > 0) {
    sectionTitle(`Flights (${data.flights.length})`);
    data.flights.forEach((f) => {
      checkPage(18);
      doc.setFont("helvetica", "bold");
      doc.text(`${f.from} → ${f.to}`, margin, y);
      doc.setFont("helvetica", "normal");
      doc.text(`~${f.currency}${f.price}`, pageWidth - margin - 30, y);
      y += 5;
      doc.setTextColor(100);
      doc.text(`${f.airline} • ${f.date} • ${f.departureTime}-${f.arrivalTime} • ${f.duration} • ${f.stops === 0 ? "Direct" : f.stops + " stop(s)"}`, margin, y);
      doc.setTextColor(60);
      y += 8;
    });
    y += 2;
  }

  // Hotels
  if (data.hotels.length > 0) {
    sectionTitle(`Hotels (${data.hotels.length})`);
    data.hotels.forEach((h) => {
      checkPage(18);
      doc.setFont("helvetica", "bold");
      doc.text(h.name, margin, y);
      doc.setFont("helvetica", "normal");
      doc.text(`~${h.currency}${h.pricePerNight}/night`, pageWidth - margin - 35, y);
      y += 5;
      doc.setTextColor(100);
      doc.text(`${"★".repeat(h.stars)} • ${h.location}`, margin, y);
      doc.setTextColor(60);
      y += 5;
      if (h.description) {
        const descLines = doc.splitTextToSize(h.description, maxWidth);
        descLines.slice(0, 2).forEach((line: string) => {
          checkPage(6);
          doc.text(line, margin, y);
          y += 5;
        });
      }
      y += 4;
    });
  }

  // Activities
  if (data.activities.length > 0) {
    sectionTitle(`Activities (${data.activities.length})`);
    data.activities.forEach((a) => {
      checkPage(14);
      doc.setFont("helvetica", "bold");
      doc.text(a.name, margin, y);
      doc.setFont("helvetica", "normal");
      doc.text(`~${a.currency}${a.price}`, pageWidth - margin - 25, y);
      y += 5;
      doc.setTextColor(100);
      doc.text(`${a.duration} • ${a.category}`, margin, y);
      doc.setTextColor(60);
      y += 8;
    });
  }

  // Itinerary
  if (data.itinerary.length > 0) {
    sectionTitle("Day-by-Day Itinerary");
    data.itinerary.forEach((day) => {
      checkPage(30);
      doc.setFont("helvetica", "bold");
      doc.text(`Day ${day.day}: ${day.title}`, margin, y);
      y += 6;
      doc.setFont("helvetica", "normal");

      [
        { label: "Morning", text: day.morning },
        { label: "Afternoon", text: day.afternoon },
        { label: "Evening", text: day.evening },
      ].forEach(({ label, text }) => {
        checkPage(12);
        doc.setTextColor(100);
        doc.text(`${label}:`, margin + 4, y);
        doc.setTextColor(60);
        const lines = doc.splitTextToSize(text, maxWidth - 8);
        lines.forEach((line: string) => {
          checkPage(6);
          doc.text(line, margin + 28, y);
          y += 5;
        });
        y += 2;
      });
      y += 4;
    });
  }

  // Budget
  const flightsCost = data.flights.reduce((s, f) => s + f.price, 0);
  const hotelsCost = data.hotels.reduce((s, h) => s + h.pricePerNight * (data.itinerary.length || 1), 0);
  const activitiesCost = data.activities.reduce((s, a) => s + a.price, 0);
  const total = flightsCost + hotelsCost + activitiesCost;
  const cur = data.flights[0]?.currency || data.hotels[0]?.currency || "$";

  if (total > 0) {
    sectionTitle("Estimated Budget");
    if (flightsCost) { doc.text(`Flights: ~${cur}${flightsCost.toLocaleString()}`, margin, y); y += 6; }
    if (hotelsCost) { doc.text(`Hotels: ~${cur}${hotelsCost.toLocaleString()}`, margin, y); y += 6; }
    if (activitiesCost) { doc.text(`Activities: ~${cur}${activitiesCost.toLocaleString()}`, margin, y); y += 6; }
    doc.setFont("helvetica", "bold");
    doc.text(`Total: ~${cur}${total.toLocaleString()}`, margin, y);
    y += 8;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(140);
    doc.text("All prices are approximate estimates. Verify on booking sites.", margin, y);
    y += 6;
  }

  // Footer
  checkPage(15);
  y += 6;
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("Jolliday — Your AI Travel Companion", margin, y);

  doc.save(`${destination.replace(/\s+/g, "-").toLowerCase()}-trip-plan.pdf`);
};
