import jsPDF from "jspdf";

type TripData = {
  title: string;
  messages: { role: string; content: string }[];
};

export const exportTripPDF = (data: TripData) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let y = 20;

  const addPage = () => {
    doc.addPage();
    y = 20;
  };

  const checkPage = (needed: number) => {
    if (y + needed > doc.internal.pageSize.getHeight() - 20) addPage();
  };

  // Title
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text(data.title, margin, y);
  y += 10;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120);
  doc.text(`Generated by Rzuma • ${new Date().toLocaleDateString()}`, margin, y);
  y += 12;
  doc.setTextColor(0);

  // Line
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  // Extract text from messages (skip JSON blocks)
  const assistantMessages = data.messages
    .filter((m) => m.role === "assistant")
    .map((m) => {
      let text = m.content;
      // Remove all code blocks
      text = text.replace(/```[\s\S]*?```/g, "");
      return text.trim();
    })
    .filter(Boolean);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");

  assistantMessages.forEach((msg, i) => {
    checkPage(20);

    if (i > 0) {
      doc.setDrawColor(230);
      doc.line(margin, y, pageWidth - margin, y);
      y += 8;
    }

    const lines = doc.splitTextToSize(msg, maxWidth);
    lines.forEach((line: string) => {
      checkPage(7);
      doc.text(line, margin, y);
      y += 6;
    });
    y += 6;
  });

  // Footer
  checkPage(20);
  y += 10;
  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text("Rzuma — Your AI Travel Companion • rzuma.lovable.app", margin, y);

  doc.save(`${data.title.replace(/\s+/g, "-").toLowerCase()}-trip-plan.pdf`);
};
